.gitignore
.travis.yml
tensorhive/cli.py
tensorhive/core/managers/InfrastructureManager.py
tensorhive/core/managers/TensorHiveManager.py
tensorhive/core/managers/ThreadedManager.py
tensorhive/core/monitors/GPUMonitor.py
tensorhive/core/monitors/Monitor.py
tensorhive/core/services/MonitoringService.py
tensorhive/core/services/Service.py
tensorhive/core/utils/NvidiaSmiParser.py
tensorhive/models/UserModel.py

Add python 3.5 support (remove f-strings, move variable annotations to comments)

---

README.md

This asciinema recording should be recorded again **before v0.2 release** for sure (conda is not neccessary there)

README.md update proposal - visual redesign (screenshots, asiinema)

---

tensorhive/api/APIServer.py
tensorhive/api/api/machines.py
tensorhive/api/api_specification.yml
tensorhive/cli.py
tensorhive/core/managers/TensorHiveManager.py
tensorhive/core/utils/Singleton.py

make TensorHiveManager a Singleton
call TensorHiveManager directly from API
delegate sig shutdown handling to API server

merge api and core cli run options

---

tensorhive/__main__.py
tensorhive/cli.py
tensorhive/config.py

Add CLI log level option (e.g. --log-level info, -l debug)

---

tensorhive/api/api/nodes.py
tensorhive/api/api_specification.yml
tensorhive/controllers/node/GetHostnamesController.py
tensorhive/controllers/node/GetMetricsController.py
tensorhive/core/monitors/GPUMonitoringBehaviour.py
tensorhive/core/utils/NvidiaSmiParser.py

- List of hostnames (all nodes) ```/nodes/hostnames```
- All metrics (all nodes) ```/nodes/metrics```
- GPU metrics (node with specific hostname) ```/nodes/{hostname}/metrics/gpu```
from:
```
"memory.total [MiB]": "1996 MiB",
"utilization.gpu [%]": "[Not Supported]",
```
to:
```
"memory.total [MiB]": 1996,
"utilization.gpu [%]": null,
```

Add infrastructure metrics to API

---

tensorhive/app/web/dev/package.json
tensorhive/app/web/dev/src/api/index.js
tensorhive/app/web/dev/src/components/dash/BaseSidebarMenu.vue
tensorhive/app/web/dev/src/components/views/NodesOverview.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/ChartsGenerator.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/LineChart.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/MetricsTable.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/NodesTable.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReservation.vue
tensorhive/app/web/dev/src/routes.js

- Navigation tabs with charts
- Representation of each node from api (metrics, resources)
-  Multiplication of blocks

Add charts

---

tensorhive/api/api_specification.yml
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarCancel.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReserve.vue
tensorhive/controllers/reservation_event/CreateReservationEventController.py
tensorhive/models/reservation_event/ReservationEventModel.py

- Issues:
- #39 Automatic date selection
- #40 Coarse-grainded date selection
- Add modal before canceling the reservation on click
- Rename some variables
- Add support for timezones: database - UTC, web application - local

Fix reservation time selection

---

tensorhive/api/api/reservations.py
tensorhive/api/api_specification.yml
tensorhive/controllers/reservation_event/CreateReservationEventController.py
tensorhive/controllers/reservation_event/ListReservationEventsController.py
tensorhive/models/reservation_event/ReservationEventModel.py

Allow web application to choose reservations sent by api:
- specify selected resources ids
- select period of time

Limit reservations sent by api to web application

---

tensorhive/app/web/dev/src/api/index.js
tensorhive/app/web/dev/src/components/views/ReserveResources.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReserve.vue
tensorhive/app/web/dev/static/fullcalendar/fullcalendar.js

- #37  Add hierarchical GPU filtering in reservations view
- Adjust cooperation with api to minimize number of reservations received by application

Add hierarchical resource filtering in calendar

---

tensorhive/app/web/dev/src/components/views/NodesOverview.vue
tensorhive/app/web/dev/src/components/views/ReserveResources.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/ChartBox.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/ChartsGenerator.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchBox.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchGenerator.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarCancel.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReserve.vue

Issue #41 View GPU processes and users in web application
Adapt resource view and nodes overview to modified api responses

Adapt web application to modified api responses

---

tensorhive/app/web/dev/src/api/index.js
tensorhive/app/web/dev/src/components/App.vue
tensorhive/app/web/dev/src/components/TheCreate.vue
tensorhive/app/web/dev/src/components/TheDash.vue
tensorhive/app/web/dev/src/components/TheLogin.vue
tensorhive/app/web/dev/src/components/TheRegister.vue
tensorhive/app/web/dev/src/components/dash/BaseSidebar.vue
tensorhive/app/web/dev/src/components/dash/BaseSidebarMenu.vue
tensorhive/app/web/dev/src/components/views/ReservationsOverview.vue
tensorhive/app/web/dev/src/components/views/UsersOverview.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchBox.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchGenerator.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarReserve.vue
tensorhive/app/web/dev/src/main.js
tensorhive/app/web/dev/src/router/index.js
tensorhive/app/web/dev/src/routes.js
tensorhive/app/web/dev/src/store/mutations.js
tensorhive/app/web/dev/src/store/state.js
tensorhive/app/web/dev/static/config/index.js

- #65 CRUD (update not in use yet) for users in web application
- User have to login before seeing any of application views
- Add header with indexes of selected resources in reservations overview
- Chip with username and logout button
- Support user roles
- Add admin panel where admin can see table with all users, create or delete user
- Prepare app for #85 - allow change of api path after application build
- Save selected resources from reservations overview and watches from node overview in local storage to handle page refreshes
- Adjust variable/file names to match api notation

Second part of web application changes

---

tensorhive/api/APIServer.py
tensorhive/app/web/AppServer.py
tensorhive/cli.py
tensorhive/core/utils/colors.py

Purely aesthetic feature:
- Highlight TensorHive name on startup and shutdown message.
- Highlight URLs of API and web app server.

Introduce colored output utility. 

---

tensorhive/models/Reservation.py

Allow reservations to be like: A.ends_at == B.starts_at

---

tensorhive/api/api_specification.yml

Connexion won't respond with its custom JSON reponse.

Disable connexion requests validator (let backend handle this)

---

README.md

The file itself is pretty explanatory https://github.com/roscisz/TensorHive/tree/feature/update_readme
It's required to fill some `TODOs` but overall it's very close to completion.
Share you thoughts.

Redesigned README.md for 0.2 release

---

setup.py

Don't override existing configuration files when `pip install`

---

requirements-dev.txt
setup.py

Fixes #118
I made some simple checks + ran test suite multiple times on a clean conda environment => seem to work, but please test it by yourself.
**I think we could use some kind of automation for dependencies, like:** https://pyup.io/help/faq/ (stumbled upon this in [MedTagger](https://github.com/jpowie01/MedTagger) repo - looks great)

Specify versions of all dependencies in `setup.py` and `requirements-dev.txt`

---

.gitignore
tensorhive/app/web/dist/static/config.json

Is this file always automatically created, so we can get rid of it from the repo?

add webapp config to gitignore

---

tensorhive/app/web/dev/src/components/views/UsersOverview.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/MySchedule.vue

Changes requested in previous pull request

---

README.md
tensorhive/hosts_config.ini

Hope you like the new look and more product-first approach :fire: :cowboy_hat_face: 
[Preview link](https://github.com/roscisz/TensorHive/tree/feature/updated_readme#tensorhive)
-------------------------
- utilization usage stats
template in repo settings
-------------------------

Redesigned, more detailed and updated README with product-focused approach

---

tensorhive/app/web/dev/src/main.js

Hi!
While going over the app familiarizing myself with all of this stuff I've came across one rather annoying issue, that is: when refreshing the page we're taken back to the login screen. This PR fixes that issue.
This is a rather common issue, the `vuex-persistedstate` plugin deals with that just fine. (by default it stores state info in the LocalStorage which is consistent with what you're doing elsewhere, but if needed we can change that to utilize cookies).
More info: https://www.npmjs.com/package/vuex-persistedstate
**Update**:
PR updated according to @filschod comments.

Fix logging out behavior after refreshing any page

---

tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue

Fixes: #205 
Checkboxes remains selected and no need to re-select them after making reservation.

Don't require re-selecting checkbox

---

migrations/env.py
migrations/versions/81c2455baab1_create_resources_table.py
migrations/versions/9d12594fe87b_create_restriction_schedules_and_.py
migrations/versions/e935d47c4cde_create_restrictions_and_secondary_tables.py
migrations/versions/ecd059f567b5_create_groups_and_user2group_tables.py
tensorhive/database.py
tensorhive/models/Group.py
tensorhive/models/Resource.py
tensorhive/models/Restriction.py
tensorhive/models/RestrictionAssignee.py
tensorhive/models/RestrictionSchedule.py
tensorhive/models/User.py
tests/conftest.py
tests/fixtures/database.py
tests/fixtures/models.py
tests/unit/models/test_group_model.py
tests/unit/models/test_resource_model.py
tests/unit/models/test_restriction_model.py
tests/unit/models/test_restrictionschedule_model.py
tests/unit/models/test_user_model.py

Fixes #261, #263, #264, #265
This adds necessary classes, migrations to extend the database according to the diagram below. After merging this the database should be fully ready for the backend to use ;)
Additionally, it adds foreign key constraints validation which was missing (for example, it allowed for creation of user reservations assigned to non-existent users - which was actually done in one of the tests).
Db diagram:

Access control - Database

---

tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarInfo.vue
tensorhive/controllers/reservation.py
tests/fixtures/controllers.py

Fix security issues in Reservation controller

---

tensorhive/app/web/dev/src/components/TheDash.vue
tensorhive/app/web/dev/src/components/views/UsersOverview.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchBox.vue
tensorhive/app/web/dev/src/components/views/nodes_overview/WatchGenerator.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendar.vue
tensorhive/app/web/dev/src/components/views/reserve_resources/FullCalendarInfo.vue
tensorhive/app/web/dev/src/components/views/users_overview/GroupsInfo.vue
tensorhive/app/web/dev/src/components/views/users_overview/UsersInfo.vue
tensorhive/app/web/dev/src/config/index.js
tensorhive/app/web/dev/src/main.js
tensorhive/app/web/dev/src/utils/scheduleUtils.js
tensorhive/app/web/dev/static/config.json
tensorhive/controllers/reservation.py
tensorhive/core/utils/ReservationVerifier.py
tensorhive/models/RestrictionSchedule.py
tests/functional/controllers/test_schedule_controller_superuser.py

These changes add groups and restrictions to Users Overview and info about restrictions for logged user to Reservations Overview.

Access control UI
